config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  resources :users

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:user][:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:user][:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      flash[:success] = "#{user.name}, successfully signed in"
      redirect_to '/'
    else
      # If user's login doesn't work, send them back to the login form.
      flash[:danger] = 'Invalid email/password combination'

      render 'new'
      # redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:success] = "User successfully created..."
      redirect_to login_path
    else
      flash[:notice] = "errors"
      redirect_to signup_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class DeckController < ApplicationController
  def index
    @decks = Deck.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="btn btn-primary">
  <head>
    <title>FlashCards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap-theme', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>FlashCards</h1>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <%= link_to "home", root_path, class: "navbar-brand" %>

    <div class="collapse navbar-collapse" id="navbarColor01">

      <ul class="navbar-nav mr-auto">
        <% if current_user %>
        <li class="nav-item">
          <%= link_to "profile", user_path(User.find(session[:user_id])), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "logout", logout_path, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "register", new_user_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>

    <% if current_user %>
      <h3>Welcome <%= User.find(session[:user_id]).name %>!</h3>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h3>Register</h3>

<%= form_for :user, :html =>  {class: 'form-inline'}, url: '/users' do |f| %>
  <p>
    <div class="form-group">
      <%= f.email_field :name, type: "text", class: "form-control", id: "exampleInputEmail1", placeholder: "name"%>
    </div>
  </p>

  <p>
    <div class="form-group">
      <%= f.email_field :email, type: "email", class: "form-control", id: "exampleInputEmail1", placeholder: "email"%>
    </div>
  </p>
  <p>
    <div class="form-group">
      <%= f.password_field :password, type: "password", class: "form-control", id: "exampleInputEmail1", placeholder: "password"%>
    </div>
  </p>

  <p>
    <div class="form-group">
      <%= f.password_field :password_confirmation, type: "password", class: "form-control", id: "exampleInputEmail1", placeholder: "password confirmation"%>
    </div>
  </p>

  <p>
    <%= f.submit 'sign up', :class => 'btn btn-primary', :name => 'sign up'%>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
</p>